### ISSUE TITLE
Umbrella ticket for EFO/GWAS clinical temporal measurement-related traits

### ISSUE THREAD

**Issue by rays22** [obophenotype/bio-attribute-ontology#105]
### Create separate tickets for creating DOS-DP trait patterns related to

- [ ] disease prognosis measurement	[EFO:0007936](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0007936)
- [ ] disease recurrence	[EFO:0004952](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0004952)
- [ ] family history	[EFO:0000493](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000493)
- [ ] illness severity status	[EFO:0007863](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0007863)
- [ ] remission	[EFO:0009785](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0009785)

These trait patterns would be used by GWAS.

**Comment by rays22** [comment]
[Clinical temporal measurement combined terms](https://docs.google.com/spreadsheets/d/1iQl7YSKPfy2vwRIcWimbrVp64brOvAxyThBzJl5e9ik) table:

CLINICAL-TEMPORAL-TERM | CLIN-TEMP-TERM-ID | DISEASE-TERM | DISEASE-TERM-ID | MONDO_HP-TERM-ID | SUGGESTED-COMBINED-TERM | PMIDS
-- | -- | -- | -- | -- | -- | --
age at diagnosis | EFO_0004918 | Alzheimer disease | MONDO_0004975 | MONDO:0004975 | age at onset of Alzheimer disease | 32589924
age at diagnosis | EFO_0004918 | asthma | MONDO_0004979 | MONDO:0004979 | age at onset of asthma | 32589924
age at diagnosis | EFO_0004918 | bladder carcinoma | MONDO_0004986 | MONDO:0004986 | age at onset of bladder carcinoma | 31277774
age at diagnosis | EFO_0004918 | cardiac arrhythmia | EFO_0004269 | MONDO:0007263 | age at onset of cardiac arrhythmia | 32589924
age at diagnosis | EFO_0004918 | cataract | MONDO_0005129 | MONDO:0005129 | age at onset of cataract | 32589924
age at diagnosis | EFO_0004918 | coronary atherosclerosis | EFO_0007938 | MONDO:0021661 | age at onset of coronary atherosclerosis | 32589924
age at diagnosis | EFO_0004918 | essential hypertension | MONDO_0001134 | MONDO:0001134 | age at onset of essential hypertension | 32589924
age at diagnosis | EFO_0004918 | hernia of the abdominal wall | HP_0004299 | HP:0004299 | age at onset of hernia of the abdominal wall | 32589924
age at diagnosis | EFO_0004918 | hyperlipidemia | MONDO_0021187 | MONDO:0021187 | age at onset of hyperlipidemia | 32589924
age at diagnosis | EFO_0004918 | osteoarthritis | MONDO_0005178 | MONDO:0005178 | age at onset of osteoarthritis | 32589924
age at diagnosis | EFO_0004918 | Parkinson disease | MONDO_0005180 | MONDO:0005180 | age at onset of Parkinson disease | 30338293\|32589924
age at diagnosis | EFO_0004918 | schizophrenia | MONDO_0005090 | MONDO:0005090 | age at onset of schizophrenia | 32589924
age at diagnosis | EFO_0004918 | type 1 diabetes mellitus | MONDO_0005147 | MONDO:0005147 | age at onset of type 1 diabetes mellitus | 33179336
age at diagnosis | EFO_0004918 | type 2 diabetes mellitus | MONDO_0005148 | MONDO:0005148 | age at onset of type 2 diabetes mellitus | 32589924
age at onset | EFO_0004847 | age-related cataract | HP_0011141 | HP:0011141 | age at onset of age-related cataract | 25352737
age at onset | EFO_0004847 | alcohol dependence | MONDO_0007079 | MONDO:0007079 | age at onset of alcohol dependence | 24962325
age at onset | EFO_0004847 | allergic disease | MONDO_0005271 | MONDO:0005271 | age at onset of allergic disease | 32603359
age at onset | EFO_0004847 | Alzheimer disease | MONDO_0004975 | MONDO:0004975 | age at onset of Alzheimer disease | 26830138\|22005931\|29107063
age at onset | EFO_0004847 | amyotrophic lateral sclerosis | MONDO_0004976 | MONDO:0004976 | age at onset of amyotrophic lateral sclerosis | 25442119\|22959728
age at onset | EFO_0004847 | asthma | MONDO_0004979 | MONDO:0004979 | age at onset of asthma | 27130862\|30929738
age at onset | EFO_0004847 | bipolar disorder | EFO_0000289 | MONDO:0004985 | age at onset of bipolar disorder | 21305692
age at onset | EFO_0004847 | Buruli ulcer disease | MONDO_0000327 | MONDO:0000327 | age at onset of Buruli ulcer disease | 32313116
age at onset | EFO_0004847 | cannabis use | EFO_0007585 | ?? MONDO:0005689 | age at onset of cannabis use | 25987507\|30003630
age at onset | EFO_0004847 | childhood onset asthma | MONDO_0005405 | MONDO:0005405 | age at onset of childhood onset asthma | 31379025\|31379025
age at onset | EFO_0004847 | coronary stenosis | EFO_1000882 | MONDO:0006715 | age at onset of coronary stenosis | 33766035
age at onset | EFO_0004847 | frontotemporal dementia | Orphanet_282 | MONDO:0017276 | age at onset of frontotemporal dementia | 28128768\|29724592
age at onset | EFO_0004847 | glioblastoma multiforme | EFO_0000519 | MONDO:0018177 | age at onset of glioblastoma multiforme | 30152087
age at onset | EFO_0004847 | Huntington disease | Orphanet_399 | MONDO:0007739 | age at onset of Huntington disease | 29750799
age at onset | EFO_0004847 | Machado-Joseph disease | MONDO_0007182 | MONDO:0007182 | age at onset of Machado-Joseph disease | 32205469
age at onset | EFO_0004847 | migraine disorder | MONDO_0005277 | MONDO:0005277 | age at onset of migraine disorder | 34380431
age at onset | EFO_0004847 | migraine with aura | MONDO_0005475 | MONDO:0005475 | age at onset of migraine with aura | 34380431
age at onset | EFO_0004847 | migraine without aura | MONDO_0011847 | MONDO:0011847 | age at onset of migraine without aura | 34380431
age at onset | EFO_0004847 | multiple sclerosis | MONDO_0005301 | MONDO:0005301 | age at onset of multiple sclerosis | 19010793
age at onset | EFO_0004847 | myopia | HP_0000545 | HP:0000545 | age at onset of myopia | 29808027
age at onset | EFO_0004847 | narcolepsy-cataplexy syndrome | MONDO_0016158 | MONDO:0016158 | age at onset of narcolepsy-cataplexy syndrome | 24204295
age at onset | EFO_0004847 | Parkinson disease | MONDO_0005180 | MONDO:0005180 | age at onset of Parkinson disease | 19772629\|26233692\|27402877\|31660654\|31755958\|30957308\|33884653
age at onset | EFO_0004847 | schizophrenia | MONDO_0005090 | MONDO:0005090 | age at onset of schizophrenia | 21688384
age at onset | EFO_0004847 | smoking initiation | EFO_0005670 | ?? MONDO:0008575 | age at smoking initiation | 24665060\|31089300
age at onset | EFO_0004847 | systemic lupus erythematosus | EFO_0002690 | MONDO:0007915 | age at onset of systemic lupus erythematosus | 29967481
age at onset | EFO_0004847 | unipolar depression | EFO_0003761 | MONDO:0002009 | age at onset of unipolar depression | 22915352
disease prognosis measurement | EFO_0007936 | Crohn's disease | EFO_0000384 | MONDO:0005011 | Crohn's disease prognosis measurement | 28067912\|29905830
disease prognosis measurement | EFO_0007936 | non-small cell lung carcinoma | EFO_0003060 | MONDO:0005233 | non-small cell lung carcinoma prognosis measurement | 34002017
disease prognosis measurement | EFO_0007936 | urinary bladder carcinoma | MONDO_0004986 | MONDO:0004986 | urinary bladder carcinoma prognosis measurement | 31277774
disease progression measurement | EFO_0008336 | adolescent idiopathic scoliosis | EFO_0005423 | MONDO:0005488 | adolescent idiopathic scoliosis progression measurement | 29016859
disease progression measurement | EFO_0008336 | age-related macular degeneration | EFO_0001365 | MONDO:0005150 | age-related macular degeneration progression measurement | 29346644\|33751636
disease progression measurement | EFO_0008336 | cerebral microbleeds | EFO_0010059 | ?? | cerebral microbleed progression measurement | 31209788
disease progression measurement | EFO_0008336 | Churg-Strauss syndrome | EFO_0007208 | MONDO:0015943 | Churg-Strauss syndrome progression measurement | 32009195
disease progression measurement | EFO_0008336 | colorectal cancer | EFO_0005842 | MONDO:0005575 | colorectal cancer progression measurement | 30738427
disease progression measurement | EFO_0008336 | Crohn's disease | EFO_0000384 | MONDO:0005011 | Crohn's disease progression measurement | 30801121
disease progression measurement | EFO_0008336 | Duchenne muscular dystrophy | Orphanet_98896 | MONDO:0010679 | Duchenne muscular dystrophy progression measurement | 30014611
disease progression measurement | EFO_0008336 | HIV infection | EFO_0000764 | MONDO:0005109 | HIV progression measurement | 28132517
disease progression measurement | EFO_0008336 | Huntington disease | Orphanet_399 | MONDO:0007739 | Huntington disease progression measurement | 28642124
disease progression measurement | EFO_0008336 | non-small cell lung carcinoma | EFO_0003060 | MONDO:0005233 | non-small-cell lung cancer progression measurement | 30207284
disease progression measurement | EFO_0008336 | Parkinson disease | MONDO_0005180 | MONDO:0005180 | Parkinson disease progression measurement | 33111402\|33958783
disease progression measurement | EFO_0008336 | periprosthetic osteolysis | EFO_0009761 | ??HP:0002797 | periprosthetic osteolysis progression measurement | 30794219
disease progression measurement | EFO_0008336 | rheumatoid arthritis | EFO_0000685 | MONDO:0008383 | rheumatoid arthritis progression measurement | 29065906
disease progression measurement | EFO_0008336 | urinary bladder carcinoma | MONDO_0004986 | MONDO:0004986 | bladder carcinoma progression measurement | 31277774
disease recurrence | EFO_0004952 | malaria | EFO_0001068 | MONDO:0005136 | malaria recurrence | 31667592\|32433338
disease recurrence | EFO_0004952 | multiple sclerosis | MONDO_0005301 | MONDO:0005301 | multiple sclerosis recurrence | 28739605\|33704824
family history | EFO_0000493 | coronary artery disease | EFO_0001645 | MONDO:0005010 | family history of coronary artery disease | 33766035
illness severity status | EFO_0007863 | hand, foot and mouth disease | EFO_0007294 | MONDO:0005779 | hand, foot and mouth disease severity measurement | 32634583
remission | EFO_0009785 | asthma | MONDO_0004979 | MONDO:0004979 | asthma remission | 29786918
remission | EFO_0009785 | hepatitis C virus infection | EFO_0003047 | MONDO:0005231 | hepatitis C virus remission | 30593799\|33119750
remission | EFO_0009785 | non-alcoholic steatohepatitis | EFO_1001249 | MONDO:0007027 | non-alcoholic steatohepatitis remission | 31832568
remission | EFO_0009785 | unipolar depression | EFO_0003761 | MONDO:0002009 | unipolar depression remission | 33589590
